language: python

services:
  - docker

install:
  - pip install flit
  - flit install --deps=develop

script:
  - pytest --cov=rice

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ghcr.io
  - docker build -t "ghcr.io/hugglesfox/rice:latest" -t "ghcr.io/hugglesfox/rice:$TRAVIS-TAG" .

deploy:
  provider: script
  script: docker push "ghcr.io/hugglesfox/rice:latest" && docker push "ghcr.io/hugglesfox/rice:$TRAVIS-TAG"
  on:
    tags: true
